In [15]:
import pandas as pd
import os

In [16]:
# plan_template = r"C:/users/Administrator/Desktop/xcx_plan.csv"
domains = r"C:\Share\df\reports\cxxu\0614\20250614-徐超信-网站统计情况.xlsx"
result_file = r"C:/users/Administrator/Desktop/cxxu_plan.csv"

# df = pd.read_csv(plan_template, encoding="gbk")  # GB18030更加强大

In [17]:
doms = pd.read_excel(domains)
# 移除"网站域名"为空的行
doms.dropna(how="all", inplace=True)
# 移除"网站域名"列中为空的行
doms.dropna(subset=["网站域名"], inplace=True)
# doms.dropna(how="all", inplace=True)
doms

,序号,域名申请日期,建站日期,网站域名,网站语言,产品类别,服务器ip,产品数量,谷歌收录,总出单数量,域名状态,Unnamed: 11,网站总数量：,有效网站总数量：,出单总数量：
0,1,2025-01-22,2025-01-25,plantasy-hogar.com,西班牙,农业种植,192.155.103.198,2.7W,0,13.0,K,NaN,5.0,3.0,NaN
1,2,2025-02-11,2025-02-13,ecoletissu.com,法语,手工,192.155.103.198,4.5W,0,1.0,K,NaN,NaN,NaN,NaN
2,3,2025-02-23,2025-02-25,tissuschic.com,法语,手工,23.239.111.204,5.5W,5.2k,2.0,NaN,NaN,NaN,NaN,NaN
3,4,2025-02-28,2025-03-01,boutiquedutissu.com,法语,手工,23.239.111.205,4.1W,8.2k,2.0,NaN,NaN,NaN,NaN,NaN
4,5,2025-03-20,2025-04-02,amicopeloso24.com,意大利,宠物,23.239.111.206,2.4W,6.2k,0.0,NaN,NaN,NaN,NaN,NaN

In [18]:
# 从doms(dataframe)中的网站域名这一列随机抽查k组(次)数据,每组数据包含3个域名
# k = 6
def get_domains_sample(domains=3):
    dms = doms["网站域名"].sample(domains, replace=False)
    # dms
    # 根据df中的表头(day,domain1,domain2,domain3,email,test_time,payment)
    # 构造合适的字典,插入到列表中,然后将此列表合并成df对象最后输出为csv文件
    # domain1,domain2,domain3=dms
    return dms


get_domains_sample()
# 在9:00~17:30之前抽一个时间t
import random
from datetime import datetime, timedelta


def get_random_time():
    """返回指定数量的域名字符串"""
    # 定义起始时间和结束时间的范围（当天）
    start_time = datetime.strptime("09:00", "%H:%M")
    end_time = datetime.strptime("17:30", "%H:%M")

    # 计算时间范围总秒数
    total_seconds = int((end_time - start_time).total_seconds())

    # 随机选择一个秒数
    random_second = random.randint(0, total_seconds)

    # 生成最终的随机时间
    t = (start_time + timedelta(seconds=random_second)).strftime("%H:%M")
    # print(t)
    return t

In [19]:
# 编写一个
def get_domains_sample_dict(domains=3):
    dms_dict = {}
    domains = get_domains_sample(domains=domains)
    for idx, domain in enumerate(domains, start=1):
        dms_dict[f"domain{idx}"] = domain
    # print(dms_dict)
    return dms_dict

In [20]:
lines = []
domains = 5
for day in range(6):

    line = {
        "day": day + 1,

        **get_domains_sample_dict(domains=domains),
        "email": "cxxu@test.com",
        "test_time": get_random_time(),
        "test_result": "",
    }
    lines.append(line)
# 将lines中的字典构造为df
df = pd.DataFrame(lines)

In [21]:
df

,day,domain1,domain2,domain3,domain4,domain5,email,test_time,test_result
0,1,boutiquedutissu.com,ecoletissu.com,tissuschic.com,plantasy-hogar.com,amicopeloso24.com,cxxu@test.com,15:27,
1,2,plantasy-hogar.com,amicopeloso24.com,boutiquedutissu.com,tissuschic.com,ecoletissu.com,cxxu@test.com,17:13,
2,3,boutiquedutissu.com,tissuschic.com,amicopeloso24.com,plantasy-hogar.com,ecoletissu.com,cxxu@test.com,09:52,
3,4,tissuschic.com,ecoletissu.com,boutiquedutissu.com,plantasy-hogar.com,amicopeloso24.com,cxxu@test.com,13:30,
4,5,ecoletissu.com,amicopeloso24.com,plantasy-hogar.com,boutiquedutissu.com,tissuschic.com,cxxu@test.com,10:20,
5,6,amicopeloso24.com,plantasy-hogar.com,boutiquedutissu.com,tissuschic.com,ecoletissu.com,cxxu@test.com,10:51,

In [22]:
df.to_csv(result_file,index=False)